general {
    lock_cmd = $HOME/.config/quickshell/mugen-shell/scripts/mugen-lock.sh
    before_sleep_cmd = $HOME/.config/quickshell/mugen-shell/scripts/mugen-lock.sh
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# === LOCKSCREEN === (timeout managed via Settings → Screen Lock Timer)
listener {
    timeout = 600
    on-timeout = $HOME/.config/quickshell/mugen-shell/scripts/mugen-lock.sh
}

# === SUSPEND ===
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
