-- Hyprland Lua config (mugen-shell), needing Hyprland 0.55+. Personal tweaks
-- belong in configs/user-overrides.lua, not here.

local HOME = os.getenv("HOME")

-- Wallpaper-following border colors are the only matugen values the compositor
-- consumes; colors.lua is regenerated by matugen (see system/matugen).
local ok_colors, colors = pcall(dofile, HOME .. "/.config/hypr/colors.lua")
if not ok_colors or type(colors) ~= "table" then
    colors = { outline = "rgba(968e98ff)", outline_variant = "rgba(4a454eff)" }
end

----------------
---- MONITORS --
----------------
-- Generic fallback; add your own `hyprctl monitors` entries to user-overrides.lua.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

hl.workspace_rule({ workspace = "1", persistent = true, default = true })
hl.workspace_rule({ workspace = "2", persistent = true })

--------------------------
---- ENVIRONMENT VARS ----
--------------------------
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
-- Prepend flatpak exports to the inherited value instead of replacing it —
-- clobbering XDG_DATA_DIRS hides every .desktop entry on NixOS.
hl.env("XDG_DATA_DIRS", HOME .. "/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:" .. (os.getenv("XDG_DATA_DIRS") or "/usr/local/share:/usr/share"))

-- IME (fcitx5). Drop this line if you don't use an IME. Only XMODIFIERS:
-- XWayland clients still go through XIM, while Wayland ones use fcitx5's
-- text-input frontend. Setting GTK_IM_MODULE forces GTK back onto the legacy
-- module path, which fcitx5 warns about on startup.
hl.env("XMODIFIERS", "@im=fcitx")

-----------------
---- AUTOSTART --
-----------------
hl.on("hyprland.start", function()
    hl.exec_cmd("fcitx5 -d --replace") -- IME; drop with the env block above
    hl.exec_cmd("thunar --daemon")     -- file-manager daemon
end)

-- mugen-shell autostart + HYPR_CONFIG_LUA (the shell's bar, Yura, blur, etc.)
dofile(HOME .. "/.config/hypr/configs/mugen-shell.lua")

-----------------------
---- LOOK AND FEEL ----
-----------------------
hl.config({
    general = {
        gaps_in     = 5,
        gaps_out    = 10,
        border_size = 2,
        col = {
            active_border   = colors.outline,
            inactive_border = colors.outline_variant,
        },
        resize_on_border = false,
        allow_tearing    = false,
        layout           = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,
        active_opacity   = 0.9,
        inactive_opacity = 0.7,
        shadow = {
            enabled      = false,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },
        dim_inactive = false,
    },

    dwindle = { preserve_split = true },
    master  = { new_status = "master" },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
        vrr                     = 1,
    },
    render = { new_render_scheduling = true },
    cursor = { no_warps = false },
})

-- Blur is regenerated by blur-preset.sh (Settings -> Blur Preset). Loaded here so
-- values survive reloads; falls back to a sane preset if the file is missing.
local ok_blur = pcall(dofile, HOME .. "/.config/hypr/configs/blur.lua")
if not ok_blur then
    hl.config({ decoration = { blur = {
        enabled = true, size = 5, passes = 3, ignore_opacity = true,
        noise = 0.02, contrast = 1.0, brightness = 1.2, xray = false,
        new_optimizations = true,
    } } })
end

----------------
---- INPUT -----
----------------
hl.config({
    input = {
        kb_layout          = "us",
        kb_variant         = "",
        kb_model           = "",
        kb_options         = "",
        kb_rules           = "",
        numlock_by_default = true,
        follow_mouse       = 1,
        sensitivity        = 0,
        touchpad = {
            natural_scroll        = true,
            tap_to_click          = true,
            disable_while_typing  = true,
        },
    },
})

--------------------
---- ANIMATIONS ----
--------------------
hl.config({ animations = { enabled = true } })

hl.curve("softIn",   { type = "bezier", points = { {0.15, 0.80}, {0.20, 1.00} } })
hl.curve("fluff",    { type = "bezier", points = { {0.05, 0.65}, {0.20, 1.00} } })
hl.curve("airy",     { type = "bezier", points = { {0.25, 0.90}, {0.15, 1.05} } })
hl.curve("fadeSoft", { type = "bezier", points = { {0.25, 0.40}, {0.30, 0.90} } })
hl.curve("breeze",   { type = "bezier", points = { {0.05, 0.80}, {0.10, 1.00} } })
hl.curve("softDown", { type = "bezier", points = { {0.20, 0.95}, {0.10, 1.00} } })
hl.curve("linear",   { type = "bezier", points = { {0.00, 0.00}, {1.00, 1.00} } })

hl.animation({ leaf = "windowsIn",        enabled = true, speed = 9, bezier = "softIn",   style = "popin 70%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 7, bezier = "fadeSoft", style = "popin 90%" })
hl.animation({ leaf = "windows",          enabled = true, speed = 7, bezier = "fluff" })
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 7, bezier = "fluff",    style = "slide" })
hl.animation({ leaf = "border",           enabled = true, speed = 6, bezier = "fadeSoft" })
hl.animation({ leaf = "fade",             enabled = true, speed = 5, bezier = "fadeSoft" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 7, bezier = "breeze",   style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 9, bezier = "softDown", style = "slidevert" })

dofile(HOME .. "/.config/hypr/configs/windowrules.lua")
dofile(HOME .. "/.config/hypr/configs/keybinds.lua")

-- Last, so a personal hl.config value wins over the one shipped above.
pcall(dofile, HOME .. "/.config/hypr/configs/user-overrides.lua")
