source = colors.conf

### MONITORS ###
# Generic fallback — works on any single or multi-monitor setup.
# To customize, run `hyprctl monitors` and replace with your own entries.
monitor = , preferred, auto, 1

workspace = 1, persistent:true, default:true
workspace = 2, persistent:true

### MY PROGRAMS ###
$terminal = kitty
$fileManager = thunar
$browser = firefox

### AUTOSTART ###
exec-once = fcitx5 -d --replace
exec-once = sh -lc 'sleep 1; ~/.config/hypr/scripts/wallp-restore.sh'

exec-once = quickshell -c mugen-shell
exec-once = ~/.config/mugen-shell/scripts/blur-preset.sh boot
exec-once = ~/.config/hypr/scripts/hypridle-auto-start.sh
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = systemctl --user start hyprpolkitagent
exec-once = thunar --daemon

### ENVIRONMENT VARIABLES ###
env = GTK_IM_MODULE,fcitx
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = SDL_IM_MODULE,fcitx
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_DATA_DIRS,$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

### LOOK AND FEEL ###
source= ~/.config/hypr/configs/looknfeel.conf

### ANIMATIONS ###
source= ~/.config/hypr/configs/UserAnimations.conf

### WINDOWRULES AND LAYERRULES ###
source = ~/.config/hypr/configs/windowrules.conf

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vfr = false
    vrr = 1
}

render {
	new_render_scheduling = true
}

### INPUT ###
source= ~/.config/hypr/configs/input.conf

### KEYBINDS ###
source= ~/.config/hypr/configs/keybinds.conf

cursor {
  no_warps = false
}
