-- Hyprland Lua config (mugen-shell). Lua counterpart of hyprland.conf, kept
-- side-by-side: Hyprland prefers this .lua when present, so removing it restores
-- the legacy .conf. Personalize monitors/env below (see `hyprctl monitors`).

local HOME = os.getenv("HOME")

-- Wallpaper-following border colors are the only matugen values the compositor
-- consumes; colors.lua is regenerated by matugen (see system/matugen).
local ok_colors, colors = pcall(dofile, HOME .. "/.config/hypr/colors.lua")
if not ok_colors or type(colors) ~= "table" then
    colors = { outline = "rgba(968e98ff)", outline_variant = "rgba(4a454eff)" }
end

----------------
---- MONITORS --
----------------
-- Generic fallback — works on any single or multi-monitor setup.
-- To customize, run `hyprctl monitors` and replace with your own entries.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

hl.workspace_rule({ workspace = "1", persistent = true, default = true })
hl.workspace_rule({ workspace = "2", persistent = true })

-----------------
---- PROGRAMS ---
-----------------
local terminal    = "kitty"
local fileManager = "thunar"
local browser     = "firefox"

--------------------------
---- ENVIRONMENT VARS ----
--------------------------
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_DATA_DIRS", HOME .. "/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share")

-- IME (fcitx5). Drop this block if you don't use an IME.
hl.env("GTK_IM_MODULE", "fcitx")
hl.env("QT_IM_MODULE", "fcitx")
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("SDL_IM_MODULE", "fcitx")

-----------------
---- AUTOSTART --
-----------------
hl.on("hyprland.start", function()
    hl.exec_cmd("fcitx5 -d --replace") -- IME; drop with the env block above
    hl.exec_cmd("thunar --daemon")     -- file-manager daemon
end)

-- mugen-shell autostart + HYPR_CONFIG_LUA (the shell's bar, Yura, blur, etc.)
dofile(HOME .. "/.config/hypr/configs/mugen-shell.lua")

-----------------------
---- LOOK AND FEEL ----
-----------------------
hl.config({
    general = {
        gaps_in     = 5,
        gaps_out    = 10,
        border_size = 2,
        col = {
            active_border   = colors.outline,
            inactive_border = colors.outline_variant,
        },
        resize_on_border = false,
        allow_tearing    = false,
        layout           = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,
        active_opacity   = 0.9,
        inactive_opacity = 0.7,
        shadow = {
            enabled      = false,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },
        dim_inactive = false,
    },

    dwindle = { preserve_split = true },
    master  = { new_status = "master" },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
        vrr                     = 1,
    },
    render = { new_render_scheduling = true },
    cursor = { no_warps = false },
})

-- Blur is regenerated by blur-preset.sh (Settings -> Blur Preset). Loaded here so
-- values survive reloads; falls back to a sane preset if the file is missing.
local ok_blur = pcall(dofile, HOME .. "/.config/hypr/configs/blur.lua")
if not ok_blur then
    hl.config({ decoration = { blur = {
        enabled = true, size = 5, passes = 3, ignore_opacity = true,
        noise = 0.02, contrast = 1.0, brightness = 1.2, xray = false,
        new_optimizations = true,
    } } })
end

----------------
---- INPUT -----
----------------
hl.config({
    input = {
        kb_layout          = "us",
        kb_variant         = "",
        kb_model           = "",
        kb_options         = "",
        kb_rules           = "",
        numlock_by_default = true,
        follow_mouse       = 1,
        sensitivity        = 0,
        touchpad = {
            natural_scroll        = true,
            tap_to_click          = true,
            disable_while_typing  = true,
        },
    },
})

--------------------
---- ANIMATIONS ----
--------------------
hl.config({ animations = { enabled = true } })

hl.curve("softIn",   { type = "bezier", points = { {0.15, 0.80}, {0.20, 1.00} } })
hl.curve("fluff",    { type = "bezier", points = { {0.05, 0.65}, {0.20, 1.00} } })
hl.curve("airy",     { type = "bezier", points = { {0.25, 0.90}, {0.15, 1.05} } })
hl.curve("fadeSoft", { type = "bezier", points = { {0.25, 0.40}, {0.30, 0.90} } })
hl.curve("breeze",   { type = "bezier", points = { {0.05, 0.80}, {0.10, 1.00} } })
hl.curve("softDown", { type = "bezier", points = { {0.20, 0.95}, {0.10, 1.00} } })
hl.curve("linear",   { type = "bezier", points = { {0.00, 0.00}, {1.00, 1.00} } })

hl.animation({ leaf = "windowsIn",        enabled = true, speed = 9, bezier = "softIn",   style = "popin 70%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 7, bezier = "fadeSoft", style = "popin 90%" })
hl.animation({ leaf = "windows",          enabled = true, speed = 7, bezier = "fluff" })
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 7, bezier = "fluff",    style = "slide" })
hl.animation({ leaf = "border",           enabled = true, speed = 6, bezier = "fadeSoft" })
hl.animation({ leaf = "fade",             enabled = true, speed = 5, bezier = "fadeSoft" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 7, bezier = "breeze",   style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 9, bezier = "softDown", style = "slidevert" })

--------------------
---- WINDOW RULES --
--------------------
hl.window_rule({ name = "quickshell-nofocus", match = { class = "^(quickshell)$" }, no_focus = true })
hl.layer_rule({ name = "quickshell-blur", match = { namespace = "quickshell" }, blur = true, ignore_alpha = 0 })

hl.window_rule({ name = "suppress-maximize", match = { class = ".*" }, suppress_event = "maximize" })
hl.window_rule({ name = "fix-xwayland-drag", match = { xwayland = true, class = "^$", title = "^$" }, no_focus = true })

hl.window_rule({ name = "pavucontrol",     match = { class = "^(org\\.pulseaudio\\.pavucontrol)$" }, float = true, size = "(monitor_w*0.5) (monitor_h*0.6)", center = true })
hl.window_rule({ name = "save-dialog",     match = { title = "^(Save As|Save a File|Pick Files)$" },  float = true, size = "(monitor_w*0.5) (monitor_h*0.6)", center = true })
hl.window_rule({ name = "open-files",      match = { initial_title = "^(Open Files)$" },               float = true, size = "(monitor_w*0.7) (monitor_h*0.6)", center = true })
hl.window_rule({ name = "jp-file-dialog",  match = { title = "^(.*ファイル.*)$" },                       float = true, size = "(monitor_w*0.5) (monitor_h*0.5)", center = true })

hl.window_rule({ name = "kitty-float",     match = { class = "^(kitty)$" },  float = true, size = "1050 600", center = true })
hl.window_rule({ name = "thunar-float",    match = { class = "^(thunar)$" }, float = true, size = "1050 600", center = true })
hl.window_rule({ name = "imv-float",       match = { class = "^(imv)$" },    float = true, size = "1050 600", center = true })
hl.window_rule({ name = "mpv-float",       match = { class = "^(mpv)$" },    float = true, size = "1050 600", center = true })

hl.window_rule({ name = "mugen-shortcuts", match = { title = "^(Mugen Shortcuts)$" }, float = true, size = "560 540", center = true })
hl.window_rule({ name = "mugen-calendar",  match = { title = "^(Mugen Calendar)$" },  float = true, size = "900 560", center = true })
hl.window_rule({ name = "mugen-settings",  match = { title = "^(Mugen Settings)$" },  float = true, size = "800 540", center = true })
hl.window_rule({ name = "steam-settings",  match = { class = "^(steam)$", title = "^(Steam設定)$" }, float = true, size = "1050 600", center = true })

------------------
---- KEYBINDS ----
------------------
local mainMod = "SUPER"

hl.bind(mainMod .. " + RETURN",    hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + backspace", hl.dsp.window.close())
hl.bind(mainMod .. " + N",         hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + B",         hl.dsp.exec_cmd(browser))

-- Move focus (vim-style hjkl)
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))

-- Cycle windows on the current workspace and raise the result
hl.bind(mainMod .. " + Tab",         hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.window.cycle_next()' && hyprctl dispatch 'hl.dsp.window.bring_to_top()'"))
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.window.cycle_next({ prev = true })' && hyprctl dispatch 'hl.dsp.window.bring_to_top()'"))

-- Workspaces
for i = 1, 5 do
    hl.bind(mainMod .. " + " .. i,         hl.dsp.focus({ workspace = tostring(i) }))
    hl.bind("ALT + SHIFT + " .. i,         hl.dsp.window.move({ workspace = tostring(i), follow = true }))
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = tostring(i), follow = false }))
end

-- Workspace scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move / resize with the mouse
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Volume keys — explicitly open the volume panel (change-detection mis-fires on sink swap)
hl.bind("code:122", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -2% && ~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh open volume"))
hl.bind("code:123", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +2% && ~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh open volume"))
hl.bind("code:121", hl.dsp.exec_cmd("pamixer --toggle-mute && ~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh open volume"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle && ~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh open volume"))

-- Brightness
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl --class backlight set +5% && ~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh open brightness"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl --class backlight set 5%- && ~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh open brightness"))

-- Fullscreen
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())

-- Screenshots
hl.bind(mainMod .. " + F12", hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/take-screenshot.sh"))
hl.bind("Print",             hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/take-screenshot.sh"))

-- Move window (vim-style hjkl)
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + SHIFT + mouse:272", hl.dsp.window.float({ action = "toggle" }), { mouse = true })
hl.bind(mainMod .. " + SHIFT + SPACE",     hl.dsp.window.float({ action = "toggle" }))

-- Special workspace
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.workspace.toggle_special("magic"))

-- Media keys
hl.bind("code:172", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("code:171", hl.dsp.exec_cmd("playerctl next"))
hl.bind("code:173", hl.dsp.exec_cmd("playerctl previous"))

-- Mugen Shell modules
hl.bind(mainMod .. " + R",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh launcher"))
hl.bind(mainMod .. " + W",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh wallpaper"))
hl.bind(mainMod .. " + P",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh powermenu"))
hl.bind(mainMod .. " + M",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh music"))
hl.bind(mainMod .. " + T",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh notification"))
hl.bind(mainMod .. " + Y",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh ai"))
hl.bind(mainMod .. " + V",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh clipboard"))
hl.bind(mainMod .. " + C",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/toggle-calendar.sh"))
hl.bind(mainMod .. " + S",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh screenshot-gallery"))
hl.bind(mainMod .. " + U",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh volume"))
hl.bind(mainMod .. " + I",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh wifi"))
hl.bind(mainMod .. " + E",         hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh bluetooth"))
hl.bind(mainMod .. " + comma",     hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/toggle-settings.sh"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/mugen-shell-ipc.sh timer"))
hl.bind(mainMod .. " + SHIFT + Y", hl.dsp.exec_cmd("qs -p ~/.config/quickshell/mugen-shell/yura-shell.qml ipc call yura toggle"))
hl.bind(mainMod .. " + slash",     hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/toggle-shortcuts.sh"))

-- Idle inhibitor toggle
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd("~/.config/quickshell/mugen-shell/scripts/idle_inhibitor.sh"))
