source = colors.conf

general {
    fractional_scaling = 2
    immediate_render = true
}

background {
    monitor =
    path = $HOME/.cache/mugen-shell/wallp/current_wallpaper_thumb.png
    color = $background
    blur_size = 8
    blur_passes = 3
    noise = 0.02
    contrast = 0.85
    brightness = 0.75
    vibrancy = 0.15
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = $primary
    font_size = 108
    font_family = M PLUS 2 Thin
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] LC_TIME=C date +"%A, %d %B"
    color = $on_surface
    font_size = 15
    font_family = M PLUS 2 Light
    position = 0, 30
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 52
    outline_thickness = 1
    dots_size = 0.18
    dots_spacing = 0.25
    dots_center = true
    dots_rounding = -1
    rounding = 26
    outer_color = $outline
    inner_color = $surface_container
    font_color = $on_surface
    check_color = $primary
    fail_color = $error
    fade_on_empty = false
    placeholder_text = <span font_style='italic'>password </span>
    shadow_passes = 2
    shadow_size = 4
    shadow_color = $shadow
    position = 0, -80
    halign = center
    valign = center
}
