-- Generated by blur-preset.sh (Settings -> Blur Preset). Loaded from hyprland.lua
-- so the values survive reloads (matugen rewriting colors on wallpaper change).
hl.config({ decoration = { blur = {
    enabled = true,
    size = 5,
    passes = 3,
    ignore_opacity = true,
    noise = 0.02,
    contrast = 1.0,
    brightness = 1.2,
    xray = false,
    new_optimizations = true,
} } })
