animations {
  enabled = yes

  bezier = softIn,      0.15, 0.80, 0.20, 1.00
  bezier = fluff,       0.05, 0.65, 0.20, 1.00
  bezier = airy,        0.25, 0.90, 0.15, 1.05
  bezier = fadeSoft,    0.25, 0.40, 0.30, 0.90
  bezier = breeze,      0.05, 0.80, 0.10, 1.00
  bezier = softDown,    0.20, 0.95, 0.10, 1.00
  bezier = linear,      0.00, 0.00, 1.00, 1.00


  animation = windowsIn,     1, 9, softIn,   popin 70%
  animation = windowsOut,    1, 7, fadeSoft, popin 90%
  animation = windows,       1, 7, fluff
  animation = windowsMove,   1, 7, fluff,   slide
  animation = border,        1, 6, fadeSoft
  animation = fade,          1, 5, fadeSoft
  animation = workspaces,    1, 7, breeze,   slide
  animation = specialWorkspace, 1, 9, softDown, slidevert
}
