# APPLICATIONS
windowrule = match:class (^(quickshell)$), no_focus on

# quickshell (layer rules)
layerrule = blur on, ignore_alpha 0, match:namespace quickshell

# pavucontrol
windowrule {
  name = pavucontrol
  match:class = (^(org\.pulseaudio\.pavucontrol)$)

  float = on
  size = (monitor_w*0.5) (monitor_h*0.6)
  center = on
}

# Ignore maximize requests from apps
windowrule = match:class (.*), suppress_event maximize

# Fix some dragging issues with XWayland (empty class/title helpers)
windowrule = match:xwayland true, match:class (^$), match:title (^$), no_focus on

# POP UPS AND DIALOGUES
windowrule {
  name = save-dialog
  match:title = (^(Save As|Save a File|Pick Files)$)

  float = on
  size = (monitor_w*0.5) (monitor_h*0.6)
  center = on
}

# Use initial_title for reliable matching
windowrule {
  name = open-files
  match:initial_title = (^(Open Files)$)

  float = on
  size = (monitor_w*0.7) (monitor_h*0.6)
  center = on
}

# File dialogs with Japanese titles
windowrule {
  name = jp-file-dialog
  match:title = (^(.*ファイル.*)$)

  float = on
  size = (monitor_w*0.5) (monitor_h*0.5)
  center = on
}

# Music
# windowrule {
#   name = ytm-zen
#   match:class = (^(zen)$)
#   match:title = (^YouTube Music.*)

#   float = on
#   size = 1020 680
#   center = on
# }

# kitty
windowrule {
  name = kitty-float
  match:class = (^(kitty)$)

  float = on
  size = 1000 600
  center = on
}

# Thunar
windowrule {
  name = thunar-float
  match:class = (^(thunar)$)

  float = on
  size = 1000 600
  center = on
}

# imv
windowrule {
  name = imv-float
  match:class = (^(imv)$)

  float = on
  size = 1000 600
  center = on
}

# mpv
windowrule {
  name = mpv-float
  match:class = (^(mpv)$)

  float = on
  size = 1000 600
  center = on
}

# steam settings
windowrule {
  name = steam-settings
  match:class = (^(steam)$)
  match:title = (^(Steam設定)$)

  float = on
  size = 1000 600
  center = on
}
