general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = hyprlock                 # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# === LOCKSCREEN === (timeout managed via Settings → Screen Lock Timer)
listener {
    timeout = 600
    on-timeout = hyprlock
}

# === SUSPEND ===
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
