decoration:blur:enabled = true
decoration:blur:size = 5
decoration:blur:passes = 3
decoration:blur:ignore_opacity = true
decoration:blur:noise = 0.02
decoration:blur:contrast = 1.0
decoration:blur:brightness = 1.2
decoration:blur:xray = false
decoration:blur:new_optimizations = true
